### ISSUE TITLE
Requires a dependency

### ISSUE THREAD

**Issue by TheRealM18** [Fexcraft/States#1]
I want to put this into the modpack that im creating, but requires the FSMM mod.
[crash-2018-05-29_19.02.43-client.txt](https://github.com/Fexcraft/States/files/2051368/crash-2018-05-29_19.02.43-client.txt)

**Comment by Fexcraft** [comment]
FSMM is a dependency, it is even written on the readme which is on the "main" page of this repository.
https://github.com/Fexcraft/States/blob/1.12.2/README.md
