### ISSUE TITLE
Major TPS drop with states 1.3.1

### ISSUE THREAD

**Issue by ProsperCraft** [Fexcraft/States#11]
TPS drops from 20 down to 1-5

Verified by removing states and it goes back to 20

Startup and shutdown times are affected.

Find attached Sampler mod nps samples for reading in VisualVM
[states.zip](https://github.com/Fexcraft/States/files/2455986/states.zip)

Here is a warmroast from spark - https://sparkprofiler.github.io/?WJK8hujpUh

**Comment by Fexcraft** [comment]
_Comment if still happening in newer versions._
