### ISSUE TITLE
Error Loading Playerdata

### ISSUE THREAD

**Issue by JuliusCaesar12** [Fexcraft/States#12]
Doesn't matter if I have foney or not, it just errors when I try /mun create.
I don't know if it's a problem with forge or the mod.

**Comment by Fexcraft** [comment]
Try an older State version (the version before this one), apparently it may be related to a recent "fix" for compability with "fake players" of some mods.

**Comment by JuliusCaesar12** [comment]
I'll see if it works

**Comment by JuliusCaesar12** [comment]
Thank you! It works!
