### ISSUE TITLE
Sign shops

### ISSUE THREAD

**Issue by MyWorldNetwork** [Fexcraft/States#15]
Not an issue as such, and more of a request for info on how sign shops work.

I am working on a set up where voting earns diamonds which can then be converted into F$ however I'd like to be able to create an Admin shop where players can buy items for F$ but cannot find any information on how to implement this

**Comment by Fexcraft** [comment]
The info was somewhere near a pinned message on the discord server, I'll see if I find a video or something about it.

**Comment by Fexcraft** [comment]
```
States Shop Sign Usage.
line '1' = [st-shop]
line '2' = account type (optional)
line '3' = price (1000 = 1f$!)
line '4' = mode (buy/sell)
```

https://cdn.discordapp.com/attachments/424351061873131521/443900271362572288/2018-05-10_00-17-07.mp4
 
Valid account types been "player", "municipality", "state", "server", funds will go/be taken from the selected type.

**Comment by MyWorldNetwork** [comment]
Theres a discord server!? Even that would be enough, I could look through it myself

**Comment by MyWorldNetwork** [comment]
Got it. Thanks.
