### ISSUE TITLE
chat blocked in single player

### ISSUE THREAD

**Issue by malthenon** [Fexcraft/States#16]
As stated in the title, My game wont allow me to use the chat in single player. Luckily, I have vanillaFix installed so it spit out an error file despite there not being a crash. From what i can see, it is breaking at line 224 in the PlayerEvents file, caused by the onMessage function.
[crash-2019-08-18_16.28.04-server.txt](https://github.com/Fexcraft/States/files/3516258/crash-2019-08-18_16.28.04-server.txt)

This is similar to the issue posted by prosperCraft in issues #5 but no chat comes through at all so i figured i would post anyway just to be on the safe side.

**Comment by Fexcraft** [comment]
Please try this version.
[States-1.3.3f.zip](https://github.com/Fexcraft/States/files/3516324/States-1.3.3f.zip)

**Comment by malthenon** [comment]
that appears to have fixed it. Thank you for the quick response.
