### ISSUE TITLE
Thut Essentials dependency repository not configured in build.gradle

### ISSUE THREAD

**Issue by Maldaris** [Fexcraft/States#17]
Current `build.gradle` does not define CurseForge as a maven repository, which leads to [Thut Essentials](https://github.com/Thutmose/ThutEssentials) to fail to resolve at build time.

Fix:
`        maven {
            name = "CurseForge"
            url = "https://minecraft.curseforge.com/api/maven/"
        }`

**Comment by Fexcraft** [comment]
Since when is that a dependency though :thinking:

**Comment by Fexcraft** [comment]
Maybe it is related to "ForgeVotifier/Voting", an optional dependency of FSMM?
I probably need to remove that code off FSMM and put into an own project.

**Comment by Fexcraft** [comment]
Voting related code should was removed, officially next release, but for development snapshots should be already up-to-date.
_Reply to this issues if there are still matters on this topic to re-open this._
