### ISSUE TITLE
MC mappings incredibly outdated

### ISSUE THREAD

**Issue by Maldaris** [Fexcraft/States#18]
The project defined MC mappings are out of date by about three years, which if developing the mod standalone don't cause too many problems. However our use case dictates that this mod be run in a dev environment parallel to a few other custom mods so that things like use protections and break protections can be upgraded by an addon to States & our core mod, which itself is an expansion for Terrafirmacraft.

We *might* be able do this upgrade ourselves but it would mean the warfare additions we intend to make would likely not make it back into the original repo via PR, as at that point we expect to treat it like a hard fork.

Is this something that could be done in the core repo? We're developing with the `stable_39` mapping.

**Comment by Fexcraft** [comment]
What would a hard fork mean releases wise? Is it intended as something private or?

Also I might see about the mappings when I get time.

**Comment by Maldaris** [comment]
Had to double check your custom license to see if this was even okay, but yes, the objective is to add Warfare to bring States up to feature parity with the Spigot plugin TownyAdvanced. (Turns out this is easier than fighting something like Sponge!) While I personally would like to contribute back, essentially what a hard fork would mean is that the code base would be architecturally/designed different such that merging our fork into the original, this repo, is unfeasible. I don't want to have to do that, but for our use case, I absolutely need to be able to map against `stable_39`

**Comment by Fexcraft** [comment]
Checked the license myself and I might need to update it a bit someday, as it was written far before I knew a lot about GitHub etc.

Wouldn't maybe an own Mod that relies on States be best? If any events or hooks are needed it could be added into the base mod.
A lot of data is anyway accessible via methods and e.g. setting a new owner etc is just calling correct methods and if something would need e.g. another function be unaccessible for a time, new checks/events could also be added.
:thinking:

**Comment by Fexcraft** [comment]
Updated FCL, FSMM and States itself to the stable_39 mappings,
it should work, but I cannot test launch it right now myself.
