### ISSUE TITLE
Blue screen

### ISSUE THREAD

**Issue by WhiteBite** [Fexcraft/States#19]
![image](https://user-images.githubusercontent.com/19576772/79919989-067b4b80-8438-11ea-9a67-56f849ddd1d3.png)
I have white screen.
![image](https://user-images.githubusercontent.com/19576772/79920012-185cee80-8438-11ea-826c-2f29d4311d1a.png)
my config

Can u add button to enter to gui?

**Comment by Fexcraft** [comment]
That GUI breaks often, it has to get fixed.

**Comment by WhiteBite** [comment]
![image](https://user-images.githubusercontent.com/19576772/79920985-fbc1b600-8439-11ea-9f5e-af32396c62c3.png)
When I click on white
