### ISSUE TITLE
[1.1.3] Crash on Startup

### ISSUE THREAD

**Issue by ireece1** [Fexcraft/States#2]
I'm the same guy who reported the load crash on FSMM, and now it's doing it for States.

https://paste.dimdev.org/uzofasemip.mccrash

It appears to be a similar issue to the capability registration in the previous version of FSMM

**Comment by Fexcraft** [comment]
🤔 I'll see about moving the code into pre-init same as in FSMM.

**Comment by Fexcraft** [comment]
Please try the 1.1.4 version.
