### ISSUE TITLE
Crash on World Join

### ISSUE THREAD

**Issue by Moose1002** [Fexcraft/States#20]
On attempting to start a world or a server the game immediately crashes.

Crash Log: [Crash Log](https://gist.github.com/Moose1002/8fe6ee826e36da27eeaf9f0d9221726b)
The world doesn't crash until States is added to the mods. Any help would be appreciated.

**Comment by Fexcraft** [comment]
Please try using the FCL version before 1.12.55 until next States release.

**Comment by Moose1002** [comment]
Yep that was the problem. Thanks for your help
