### ISSUE TITLE
Crash, thats all i can say

### ISSUE THREAD

**Issue by gatoborrachon** [Fexcraft/States#21]
well i have many other mods, but i have too the 2 dependencies it requires so idk what exactly could be missing, the map i played is super flat
https://pastebin.com/it5Znvb8

**Comment by Fexcraft** [comment]
Use latest FCL with States 1.5.0,
Use 1-2 versions lower FCL for States 1.4.x

**Comment by gatoborrachon** [comment]
well, it worked
