### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by teagan75** [Fexcraft/States#22]
Any chance adding the ability to do 3D zones to create apartments? 

Also, when do you think companies will be live?

**Comment by Fexcraft** [comment]
Such "zones" been planned. About companies hard to tell.
 On the discord server there been recently a large conversation about features, and there might be a large rework of States first, depends how things turn out.

**Comment by teagan75** [comment]
Glad to see this mod is getting updates. It is the best mod with most of the features I want (other than 3D zones). The company zones are intriguing which is why I asked.

**Comment by Fexcraft** [comment]
Will be part of Land-Developer, States is discontinued.
