### ISSUE TITLE
Plan to supported high mc version?

### ISSUE THREAD

**Issue by CornWorld** [Fexcraft/States#24]
Plan to supported high mc version?
Just like 1.16.5

I am wondering how magic effect it will make

**Comment by Fexcraft** [comment]
Lack of time and hardware.

**Comment by CornWorld** [comment]
oh.....
That's the worst info I got today

**Comment by Fexcraft** [comment]
I still got a couple things to finish in various 1.12 mods, and anything past 1.12 seems generally more resource hungry on the computer alone in _vanilla_.
