### ISSUE TITLE
Server crash when Ice and Fire dragons try to destroy.

### ISSUE THREAD

**Issue by ProsperCraft** [Fexcraft/States#3]
https://gist.github.com/ProsperCraft/1a57a9379bb413358b68b92bd42d0ed7

java.lang.UnsupportedOperationException: Attempted to call Event#setCanceled() on a non-cancelable event of type: net.minecraftforge.event.world.ExplosionEvent.Detonate
    at net.minecraftforge.fml.common.eventhandler.Event.setCanceled(Event.java:96)

Modpack - Ancient TownCraft [https://minecraft.curseforge.com/projects/ancient-towncraft](url)

**Comment by Fexcraft** [comment]
🤔

**Comment by ProsperCraft** [comment]
Could be related to this - https://github.com/Alex-the-666/Ice_and_Fire/issues/1054

Or this - https://github.com/Alex-the-666/Ice_and_Fire/issues/1060

**Comment by Fexcraft** [comment]
either way, main issue may be still that
```
java.lang.UnsupportedOperationException: Attempted to call Event#setCanceled() on a non-cancelable event of type: net.minecraftforge.event.world.ExplosionEvent.Detonate
    at net.minecraftforge.fml.common.eventhandler.Event.setCanceled(Event.java:96)
    at net.fexcraft.mod.states.events.WorldEvents.onExplosion(WorldEvents.java:82)
```
Apparently it is a non-cancellable event (maybe it is another one than I used back in FSU times).
I'll see about this when I get time.

**Comment by Fexcraft** [comment]
Fixed on States' end, could get improved someday to be configurable.
