### ISSUE TITLE
Suggestion: Support for Enderpay

### ISSUE THREAD

**Issue by Boymann** [Fexcraft/States#4]
As stated in the title, would it be possible to add compatibility for Enderpay?

**Comment by Fexcraft** [comment]
What is `Enderpay`?

**Comment by Boymann** [comment]
It's an economy/currency mod. https://minecraft.curseforge.com/projects/enderpay

**Comment by Fexcraft** [comment]
Hmm, so it uses items as money?
In FSMM you can configure other modded items to be registered
as FSMM money (aka work with the ATM, etc.)
Do not know how possible it would be to use FSMM money in that mod.
