### ISSUE TITLE
NPE fexcraft.mod.states.events.PlayerEvents.checkAccess

### ISSUE THREAD

**Issue by ProsperCraft** [Fexcraft/States#6]
https://gist.github.com/ProsperCraft/f84d92c1afef511cf8f0beca6563f471

One of my players sent this crash to me, but didn't tell me how he did it, will get that info from him and post it if needed.

P.S the issue link isn't filled in for the States projet page.

**Comment by ProsperCraft** [comment]
Another one from a different player placing a lilly pad on water.

https://paste.dimdev.org/ugigenejeq.mccrash

Note- that States is disabled on the server needs a null check?

**Comment by Fexcraft** [comment]
What do you mean with disabled on server?

Also I added the link to here on curseforge.

**Comment by Fexcraft** [comment]
There is no code on these lines, 🤔

**Comment by ProsperCraft** [comment]
The jar file, is disabled on the server because it breaks the floo network which we rely on, but is still active on the client.  I renamed hte states.jar to states.jar.disabled so the server would not load it.

So what we have here is a case of the client expecting something from the server I would guess and it doesn't get it, thereby needing a null check? (not a programmer just a guess)

**Comment by Fexcraft** [comment]
Are those clients connected to the server? that method should be only ran server side.

**Comment by ProsperCraft** [comment]
Server crash with similar stacktrace - https://gist.github.com/ProsperCraft/c767faf29f2e2f596d2e63ec5c2438a6

A machine was trying to interact and caused the crash.

**Comment by Fexcraft** [comment]
Hmm, I added the null check for capabilities and that fixed it, or?
Sadly I do not know why (if it's using "fakeplayers") it isn't attaching Capabilities to them
(that's internal/forge stuff), as such not holding States data to process .

**Comment by ProsperCraft** [comment]
Would love to test a fix if you can pin it down.

**Comment by Fexcraft** [comment]
🤔 oh demn, by now I messed up my copy of States, added a new Mail system, which actually uses.. items.

**Comment by ProsperCraft** [comment]
And what is wrong with that?

**Comment by Fexcraft** [comment]
New blocks/items, as that needs installation on both sides.
Also the methods/functions to set/update mailboxes aren't done/made yet.

**Comment by ProsperCraft** [comment]
Looks like a good fix, let me know when we can test it in a build.

**Comment by ProsperCraft** [comment]
Didn't fix it - 
https://gist.github.com/ProsperCraft/149f378a897476b82cf99474ab24114d

**Comment by ProsperCraft** [comment]
Resolved with the fix posted today.
