### ISSUE TITLE
NPE in console  fexcraft.mod.states.util.StatesPermissions.hasPermission(

### ISSUE THREAD

**Issue by ProsperCraft** [Fexcraft/States#9]
https://gist.github.com/ProsperCraft/1837e1fd9fb98c53c0f3e11ab9af60c4

**Comment by ProsperCraft** [comment]
bottom half - 

https://gist.github.com/ProsperCraft/9ee72fba802c2b4ed68156aa741b63fc

**Comment by Fexcraft** [comment]
Probable cause is missing/invalid(incompletly loaded) PlayerCapability.

**Comment by Fexcraft** [comment]
_StatesPermissions.class no longer exists._
